apiVersion: v1
kind: Secret
metadata:
  name: zenith-secret
  namespace: zenith
type: Opaque
stringData:
  # In a real environment, you should use base64 encoding under 'data:', 
  # but stringData lets us write it as plain text and kubernetes converts it
  JWT_SECRET: "this-is-a-very-secret-key-for-development"
